/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package anagram_kt

import org.junit.Test
import org.junit.Assert
import com.sun.source.tree.ThrowTree


class AppTest {
    
    @Test fun whenStringNullExceptionThrown() {
        Assert.assertThrows(IllegalArgumentException::class.java){
            var str : String? = null; 
            var test = Anagram(str); 
        }
    }

    @Test fun whenListNullExceptionThrown() {
        Assert.assertThrows(IllegalArgumentException::class.java){
            var lst : List<String>? = null; 
            var test = Anagram(lst); 
        }
    }
    @Test fun ifListHasNoElements(){
        Assert.assertThrows(IllegalArgumentException::class.java){
            var list : List<String>? = listOf<String>()
            var test = Anagram(list)
        }
    }
    @Test fun ListHasElements(){
        var list : List<String>? = listOf<String>("hola", "adios", "adois")
        var test = Anagram(list)
        var actualResult = test.toList()
        var expectedResult = listOf<List<String>>(listOf<String>("adios", "adois"))
        Assert.assertEquals(expectedResult, actualResult)
    }

    @Test fun ListHasMultipleAnagrams(){
        var list : List<String>? = listOf<String>("amor", "roma", "mora", "ramo", "romo", "moro")
        var test = Anagram(list)
        var actualResult = test.toList()
        var expectedResult = listOf<List<String>>(listOf<String>("amor", "roma", "mora", "ramo"), listOf<String>("romo", "moro"))
        Assert.assertEquals(expectedResult, actualResult)
    }

}
