/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package anagram_kt

fun main(args: Array<String>) {
    if(args.size < 2){
        var init = System.currentTimeMillis()
        val anagram = Anagram(args[0])
        anagram.print();
        var end = System.currentTimeMillis()
        var diff = end - init
        println("Time ellapsed: "+diff+"ms")
    }
        
    else{
        println("Cantidad de argumentos inválida")
    }
   
}
