/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package anagram_kt

fun main() {
    var list : List<String>? = listOf<String>("hola", "adios", "adois")
    var test = Anagram(list)
    var listdepruebaparaserbienduro = test.toList()
    println(listdepruebaparaserbienduro) 
   
}
